name: test_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.0.17
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  uuid: ^3.0.7
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.jpg"

flutter_native_splash:
  color: "#6A4DBA"
  image: assets/icons/splash.png
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true

  android_12:
    image: assets/icons/splash.png
    icon_background_color: "#6A4DBA"
    android_gravity: center
    ios_content_mode: center


flutter:

  uses-material-design: true

  assets:
    - assets/icons/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700